# Site Settings
title:              Jesse Lopez 
description:
baseurl:            #"/Lagrange"
url:                "https://jesse-lopez.com"
github:
  url:               "https://yosoyjay.github.io"
author:
  name:              "jesse lopez"
  email:             "yosoyjay@gmail.com"
  twitter:           "_yosoyjay"
  github:            "yosoyjay"
  linkedin:          "yosoyjay"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
